/* ============================================================================
   HIRINGTEAM EXTRACT QUERY
   ----------------------------------------------------------------------------
   PURPOSE:
   Builds the HiringTeam HDL business object record by unpivoting collaborator
   and manager attributes captured on the same checklist tasks used by the
   JobRequisition query. Each collaborator/manager becomes one output row,
   linked to the same auto-generated REQUISITIONNUMBER.

   PLACEHOLDERS TO REPLACE BEFORE USE:
     <TASK_NAME_TAM_1>       - TA Manager Alignment task name
     <TASK_NAME_TAM_2>       - TA Manager Approval task name
     <TASK_NAME_INTAKE_1..4> - Intake Meeting Schedule task names
     <TASK_NAME_POSITION_SELECTION> - Position Selection task name
     <MANAGER_TYPE_CODE>     - HDL collaborator type code for the manager role
   ============================================================================ */

WITH
LATEST_REQ AS (
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(REQUISITION_NUMBER, '[0-9]+$'))), 0) AS LATEST_NUM
    FROM   IRC_REQUISITIONS_VL
),

TAM_RAW AS (
    SELECT 
           PAT.ALLOCATED_CHECKLIST_ID AS JOIN_CHECKLIST_ID
          ,PAT.ATTRIBUTE1, PAT.ATTRIBUTE2, PAT.ATTRIBUTE3, PAT.ATTRIBUTE4, PAT.ATTRIBUTE5
    FROM   PER_ALLOCATED_TASKS     PAT
          ,PER_ALLOCATED_TASKS_TL  PAT_TL
    WHERE  PAT.ALLOCATED_TASK_ID  = PAT_TL.ALLOCATED_TASK_ID
    AND PAT_TL.LANGUAGE = 'US'
    AND PAT_TL.TASK_NAME IN ('<TASK_NAME_TAM_1>', '<TASK_NAME_TAM_2>')
    UNION ALL
    SELECT PAT.ABS_ALLOCATED_CHECKLIST_ID
          ,PAT.ATTRIBUTE1, PAT.ATTRIBUTE2, PAT.ATTRIBUTE3, PAT.ATTRIBUTE4, PAT.ATTRIBUTE5
    FROM   PER_ALLOCATED_TASKS     PAT
          ,PER_ALLOCATED_TASKS_TL  PAT_TL
    WHERE  PAT.ALLOCATED_TASK_ID  = PAT_TL.ALLOCATED_TASK_ID
    AND PAT_TL.LANGUAGE = 'US'
    AND PAT_TL.TASK_NAME IN ('<TASK_NAME_TAM_1>', '<TASK_NAME_TAM_2>')
    AND PAT.ABS_ALLOCATED_CHECKLIST_ID IS NOT NULL
),
TAM_ALL AS (
    SELECT JOIN_CHECKLIST_ID, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5
    FROM (
        SELECT T.*,
               ROW_NUMBER() OVER (PARTITION BY JOIN_CHECKLIST_ID ORDER BY ATTRIBUTE1) AS RN
        FROM   TAM_RAW T
    )
    WHERE RN = 1
),

INT_RAW AS (
    SELECT 
           PAT.ALLOCATED_CHECKLIST_ID AS JOIN_CHECKLIST_ID
          ,PAT.ALLOCATED_TASK_ID
    FROM   PER_ALLOCATED_TASKS     PAT
          ,PER_ALLOCATED_TASKS_TL  PAT_TL
    WHERE  PAT.ALLOCATED_TASK_ID  = PAT_TL.ALLOCATED_TASK_ID
    AND PAT_TL.LANGUAGE = 'US'
    AND PAT.STATUS = 'COM'
    AND PAT_TL.TASK_NAME IN (
                '<TASK_NAME_INTAKE_1>'
                ,'<TASK_NAME_INTAKE_2>'
                ,'<TASK_NAME_INTAKE_3>'
                ,'<TASK_NAME_INTAKE_4>'
           )
    UNION ALL
    SELECT PAT.ABS_ALLOCATED_CHECKLIST_ID
          ,PAT.ALLOCATED_TASK_ID
    FROM   PER_ALLOCATED_TASKS     PAT
          ,PER_ALLOCATED_TASKS_TL  PAT_TL
    WHERE  PAT.ALLOCATED_TASK_ID  = PAT_TL.ALLOCATED_TASK_ID
    AND PAT_TL.LANGUAGE = 'US'
    AND PAT.STATUS = 'COM'
    AND PAT_TL.TASK_NAME IN (
                 '<TASK_NAME_INTAKE_1>'
                ,'<TASK_NAME_INTAKE_2>'
                ,'<TASK_NAME_INTAKE_3>'
                ,'<TASK_NAME_INTAKE_4>'
           )
    AND PAT.ABS_ALLOCATED_CHECKLIST_ID IS NOT NULL
),
INT_ALL AS (
    SELECT JOIN_CHECKLIST_ID, ALLOCATED_TASK_ID
    FROM (
        SELECT I.*,
               ROW_NUMBER() OVER (PARTITION BY JOIN_CHECKLIST_ID ORDER BY ALLOCATED_TASK_ID) AS RN
        FROM   INT_RAW I
    )
    WHERE RN = 1
),

SLM_RAW AS (
    SELECT 
           PAT.ALLOCATED_CHECKLIST_ID AS JOIN_CHECKLIST_ID
          ,PAT.ALLOCATED_TASK_ID
          ,PAT.ATTRIBUTE23
    FROM   PER_ALLOCATED_TASKS     PAT
          ,PER_ALLOCATED_TASKS_TL  PAT_TL
    WHERE  PAT.ALLOCATED_TASK_ID  = PAT_TL.ALLOCATED_TASK_ID
    AND PAT_TL.LANGUAGE = 'US'
    AND PAT_TL.TASK_NAME IN (
                 '<TASK_NAME_INTAKE_1>'
                ,'<TASK_NAME_INTAKE_2>'
                ,'<TASK_NAME_INTAKE_3>'
                ,'<TASK_NAME_INTAKE_4>'
           )
    AND PAT.ATTRIBUTE23 IS NOT NULL
    UNION ALL
    SELECT PAT.ABS_ALLOCATED_CHECKLIST_ID
          ,PAT.ALLOCATED_TASK_ID
          ,PAT.ATTRIBUTE23
    FROM   PER_ALLOCATED_TASKS     PAT
          ,PER_ALLOCATED_TASKS_TL  PAT_TL
    WHERE  PAT.ALLOCATED_TASK_ID  = PAT_TL.ALLOCATED_TASK_ID
    AND PAT_TL.LANGUAGE = 'US'
    AND PAT_TL.TASK_NAME IN (
                '<TASK_NAME_INTAKE_1>'
                ,'<TASK_NAME_INTAKE_2>'
                ,'<TASK_NAME_INTAKE_3>'
                ,'<TASK_NAME_INTAKE_4>'
           )
    AND PAT.ATTRIBUTE23 IS NOT NULL
    AND PAT.ABS_ALLOCATED_CHECKLIST_ID IS NOT NULL
),
SLM_ALL AS (
    SELECT JOIN_CHECKLIST_ID
          ,ATTRIBUTE23 AS SLMANAGER
    FROM (
        SELECT S.*,
               ROW_NUMBER() OVER (PARTITION BY JOIN_CHECKLIST_ID ORDER BY ALLOCATED_TASK_ID) AS RN
        FROM   SLM_RAW S
    )
    WHERE RN = 1
),

POS_ALL AS (
    SELECT
           POS.ALLOCATED_CHECKLIST_ID AS JOIN_CHECKLIST_ID
          ,POS.ATTRIBUTE1, POS.ATTRIBUTE2
    FROM   PER_ALLOCATED_TASKS     POS
          ,PER_ALLOCATED_TASKS_TL  POS_TL
    WHERE  POS.ALLOCATED_TASK_ID  = POS_TL.ALLOCATED_TASK_ID
    AND POS_TL.LANGUAGE = 'US'
    AND POS_TL.TASK_NAME = '<TASK_NAME_POSITION_SELECTION>'
    AND POS.ATTRIBUTE1 IN ('Existing Position', 'New Position')
    UNION ALL
    SELECT POS.ABS_ALLOCATED_CHECKLIST_ID
          ,POS.ATTRIBUTE1, POS.ATTRIBUTE2
    FROM   PER_ALLOCATED_TASKS     POS
          ,PER_ALLOCATED_TASKS_TL  POS_TL
    WHERE  POS.ALLOCATED_TASK_ID  = POS_TL.ALLOCATED_TASK_ID
    AND POS_TL.LANGUAGE = 'US'
    AND POS_TL.TASK_NAME = '<TASK_NAME_POSITION_SELECTION>'
    AND POS.ATTRIBUTE1 IN ('Existing Position', 'New Position')
    AND POS.ABS_ALLOCATED_CHECKLIST_ID IS NOT NULL
),

REQNUM_BASE AS (
    SELECT 
           DISTINCT PAC.ALLOCATED_CHECKLIST_ID
    FROM   PER_ALLOCATED_CHECKLISTS PAC
          ,POS_ALL
          ,TAM_ALL
          ,PER_ALL_ASSIGNMENTS_M    PAAM
          ,INT_ALL
    WHERE  PAC.CHECKLIST_STATUS = 'COM'
    AND POS_ALL.JOIN_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
    AND TAM_ALL.JOIN_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
    AND PAAM.ASSIGNMENT_ID = PAC.ASSIGNMENT_ID
    AND TRUNC(SYSDATE) BETWEEN PAAM.EFFECTIVE_START_DATE AND PAAM.EFFECTIVE_END_DATE
    AND INT_ALL.JOIN_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
    AND (
            ( POS_ALL.ATTRIBUTE1 = 'Existing Position'
              AND EXISTS (
                    SELECT 1
                    FROM   HR_ALL_POSITIONS_F_VL H2
                    WHERE  H2.POSITION_CODE = TRIM(SUBSTR(POS_ALL.ATTRIBUTE2, INSTR(POS_ALL.ATTRIBUTE2, '-', -1) + 1))
                    AND TRUNC(SYSDATE) BETWEEN H2.EFFECTIVE_START_DATE AND H2.EFFECTIVE_END_DATE
                    AND EXISTS (SELECT 1 FROM FUN_ALL_BUSINESS_UNITS_V BUX WHERE BUX.BU_ID = H2.BUSINESS_UNIT_ID)
                  )
            )
         OR
            ( POS_ALL.ATTRIBUTE1 = 'New Position'
              AND EXISTS (SELECT 1 FROM FUN_ALL_BUSINESS_UNITS_V BUY WHERE BUY.BU_ID = PAAM.BUSINESS_UNIT_ID)
            )
        )
    AND NOT EXISTS (
        SELECT 1
        FROM	HRC_INTEGRATION_KEY_MAP HIM
        WHERE	HIM.OBJECT_NAME = 'Requisition'
        AND HIM.SOURCE_SYSTEM_ID = TO_CHAR(PAC.ALLOCATED_CHECKLIST_ID)
    )
),
REQNUM_MAP AS (
    SELECT ALLOCATED_CHECKLIST_ID
          ,(SELECT LATEST_NUM FROM LATEST_REQ)
             + ROW_NUMBER() OVER (ORDER BY ALLOCATED_CHECKLIST_ID) AS REQUISITIONNUMBER
    FROM REQNUM_BASE
)

SELECT
     AC_ID
    ,REQUISITIONNUMBER
    ,TRIM(SUBSTR(COLLAB, 1, INSTR(COLLAB, '-') - 1)) AS COLLAB_PERSONNUMBER
    ,'ORA_COLLABORATOR' AS MEMBERTYPE
    ,CASE
        WHEN COLLAB_TYPE IN ('COLLABORATOR1', 'COLLABORATOR2', 'COLLABORATOR3') THEN 'ORA_HIRING_TEAM_COLLABORATOR'
        WHEN COLLAB_TYPE = 'SLMANAGER' THEN '<MANAGER_TYPE_CODE>'
     END AS COLLABORATORTYPE
FROM (
    SELECT
         PAC.ALLOCATED_CHECKLIST_ID AS AC_ID
        ,RM.REQUISITIONNUMBER       AS REQUISITIONNUMBER
        ,TAM_ALL.ATTRIBUTE2 AS COLLABORATOR1
        ,TAM_ALL.ATTRIBUTE3 AS COLLABORATOR2
        ,TAM_ALL.ATTRIBUTE4 AS COLLABORATOR3
        ,SLM_ALL.SLMANAGER  AS SLMANAGER
    FROM
         PER_ALLOCATED_CHECKLISTS PAC
        ,TAM_ALL
        ,SLM_ALL
        ,REQNUM_MAP RM
    WHERE 1=1
        AND PAC.CHECKLIST_STATUS = 'COM'
        AND TAM_ALL.JOIN_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
        AND SLM_ALL.JOIN_CHECKLIST_ID (+) = PAC.ALLOCATED_CHECKLIST_ID
        AND RM.ALLOCATED_CHECKLIST_ID (+) = PAC.ALLOCATED_CHECKLIST_ID
       /* AND (PAC.ALLOCATED_CHECKLIST_ID = :P_ALLOCATED_CHECKLIST_ID OR :P_ALLOCATED_CHECKLIST_ID IS NULL) */
)
UNPIVOT INCLUDE NULLS (
    COLLAB FOR COLLAB_TYPE IN (COLLABORATOR1, COLLABORATOR2, COLLABORATOR3, SLMANAGER)
)
WHERE COLLAB IS NOT NULL
ORDER BY AC_ID, COLLAB_TYPE
