/* ============================================================================
   JOBREQUISITION EXTRACT QUERY
   ----------------------------------------------------------------------------
   PURPOSE:
   Builds the JobRequisition HDL business object record from a completed
   Journey/Checklist. Run via HCM Extract; output is formatted by
   an e-Text template into a .dat file consumed by HCM Data Loader (HDL) to
   create Job Requisitions in Oracle Recruiting Cloud.

   SCOPE:
   Only processes checklists with CHECKLIST_STATUS = 'COM' for the journey
   identified by <CHECKLIST_ID>, and excludes any checklist already present
   in HRC_INTEGRATION_KEY_MAP (i.e., already loaded).

   PLACEHOLDERS TO REPLACE BEFORE USE:
     <CHECKLIST_ID>                  - target checklist/journey ID
     <TASK_NAME_TAM_1>               - TA Manager Alignment task name
     <TASK_NAME_TAM_2>               - TA Manager Approval task name
     <TASK_NAME_INTAKE_1..4>         - Intake Meeting Schedule task names
     <TASK_NAME_POSITION_SELECTION>  - Position Selection task name
     <TASK_NAME_JOB_DESC>            - Job Description/Position creation task name
     <UDT_USER_TABLE>                - UDT user table name for CSP lookup
     <UST_USER_COLUMN>               - UDT user column name for CSP lookup
     <SOURCE_SYSTEM_OWNER>           - HDL SOURCESYSTEMOWNER value
   ============================================================================ */

WITH
FUNCTION GET_DEPARTMENT_NAME(P_ORG_ID NUMBER) RETURN VARCHAR2 DETERMINISTIC AS
    LV_DEPT_NAME VARCHAR2(200);
BEGIN
    SELECT HAUFT_DEP.NAME
    INTO LV_DEPT_NAME
    FROM HR_ORG_UNIT_CLASSIFICATIONS_F HOUCF_DEP
          ,HR_ALL_ORGANIZATION_UNITS_F HAOUF_DEP
          ,HR_ORGANIZATION_UNITS_F_TL HAUFT_DEP
    WHERE HAOUF_DEP.ORGANIZATION_ID = HAUFT_DEP.ORGANIZATION_ID
    AND HAOUF_DEP.ORGANIZATION_ID = HOUCF_DEP.ORGANIZATION_ID
    AND HOUCF_DEP.CLASSIFICATION_CODE = 'DEPARTMENT'
    AND HOUCF_DEP.ORGANIZATION_ID = P_ORG_ID
    AND HAUFT_DEP.LANGUAGE = 'US'
    AND TRUNC(SYSDATE) BETWEEN HOUCF_DEP.EFFECTIVE_START_DATE AND HOUCF_DEP.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN HAOUF_DEP.EFFECTIVE_START_DATE AND HAOUF_DEP.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN HAUFT_DEP.EFFECTIVE_START_DATE AND HAUFT_DEP.EFFECTIVE_END_DATE;
    RETURN LV_DEPT_NAME;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END;
FUNCTION GET_DEPARTMENT_ORG_ID(P_ORG_ID NUMBER) RETURN VARCHAR2 DETERMINISTIC AS
    LV_ORG_ID VARCHAR2(200);
BEGIN
    SELECT TO_CHAR(HAOUF_DEP.ORGANIZATION_ID)
    INTO LV_ORG_ID
    FROM HR_ORG_UNIT_CLASSIFICATIONS_F HOUCF_DEP
          ,HR_ALL_ORGANIZATION_UNITS_F HAOUF_DEP
          ,HR_ORGANIZATION_UNITS_F_TL HAUFT_DEP
    WHERE HAOUF_DEP.ORGANIZATION_ID = HAUFT_DEP.ORGANIZATION_ID
    AND HAOUF_DEP.ORGANIZATION_ID = HOUCF_DEP.ORGANIZATION_ID
    AND HOUCF_DEP.CLASSIFICATION_CODE = 'DEPARTMENT'
    AND HOUCF_DEP.ORGANIZATION_ID = P_ORG_ID
    AND HAUFT_DEP.LANGUAGE = 'US'
    AND TRUNC(SYSDATE) BETWEEN HOUCF_DEP.EFFECTIVE_START_DATE AND HOUCF_DEP.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN HAOUF_DEP.EFFECTIVE_START_DATE AND HAOUF_DEP.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN HAUFT_DEP.EFFECTIVE_START_DATE AND HAUFT_DEP.EFFECTIVE_END_DATE;
    RETURN LV_ORG_ID;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END;
FUNCTION GET_ORG_ID_BY_POSITION(P_POSITION_CODE VARCHAR2) RETURN VARCHAR2 DETERMINISTIC AS
    LV_ORG_ID VARCHAR2(200);
BEGIN
    SELECT TO_CHAR(ORGANIZATION_ID)
    INTO LV_ORG_ID
    FROM HR_ALL_POSITIONS_F_VL
    WHERE POSITION_CODE = P_POSITION_CODE
    AND TRUNC(SYSDATE) BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE
    AND ROWNUM = 1;
    RETURN LV_ORG_ID;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END;
FUNCTION GET_JOB_BY_JOB_ID(P_JOB_ID NUMBER) RETURN VARCHAR2 DETERMINISTIC AS
    LV_JOB_NAME VARCHAR2(200);
BEGIN
    SELECT NAME
    INTO LV_JOB_NAME
    FROM PER_JOBS_F_TL
    WHERE JOB_ID = P_JOB_ID
    AND LANGUAGE = 'US'
    AND TRUNC(SYSDATE) BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE;
    RETURN LV_JOB_NAME;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END;
FUNCTION GET_JOB_BY_POSITION(P_POSITION_CODE VARCHAR2) RETURN VARCHAR2 DETERMINISTIC AS
    LV_JOB_NAME VARCHAR2(200);
BEGIN
    SELECT JOB.NAME
    INTO LV_JOB_NAME
    FROM HR_ALL_POSITIONS_F_VL HAPF
          ,PER_JOBS_F_TL JOB
    WHERE HAPF.POSITION_CODE = P_POSITION_CODE
    AND TRUNC(SYSDATE) BETWEEN HAPF.EFFECTIVE_START_DATE AND HAPF.EFFECTIVE_END_DATE
    AND JOB.JOB_ID = HAPF.JOB_ID
    AND JOB.LANGUAGE = 'US'
    AND TRUNC(SYSDATE) BETWEEN JOB.EFFECTIVE_START_DATE AND JOB.EFFECTIVE_END_DATE
    AND ROWNUM = 1;
    RETURN LV_JOB_NAME;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END;
FUNCTION GET_GRADE_NAME(P_GRADE_ID NUMBER) RETURN VARCHAR2 DETERMINISTIC AS
    LV_GRADE_NAME VARCHAR2(200);
BEGIN
    SELECT NAME
    INTO LV_GRADE_NAME
    FROM PER_GRADES_F_TL
    WHERE GRADE_ID = P_GRADE_ID
    AND LANGUAGE = 'US'
    AND TRUNC(SYSDATE) BETWEEN EFFECTIVE_START_DATE AND EFFECTIVE_END_DATE;
    RETURN LV_GRADE_NAME;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END;
FUNCTION GET_BU_BY_POSITION(P_POSITION_CODE VARCHAR2) RETURN VARCHAR2 DETERMINISTIC AS
    LV_BU_NAME VARCHAR2(200);
BEGIN
    SELECT BU.BU_NAME
    INTO LV_BU_NAME
    FROM HR_ALL_POSITIONS_F_VL HAPF
          ,FUN_ALL_BUSINESS_UNITS_V BU
    WHERE HAPF.POSITION_CODE = P_POSITION_CODE
    AND TRUNC(SYSDATE) BETWEEN HAPF.EFFECTIVE_START_DATE AND HAPF.EFFECTIVE_END_DATE
    AND HAPF.BUSINESS_UNIT_ID = BU.BU_ID
    AND ROWNUM = 1;
    RETURN LV_BU_NAME;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END;
FUNCTION GET_LEGAL_EMPLOYER(P_ASSIGNMENT_ID NUMBER) RETURN VARCHAR2 DETERMINISTIC AS
    LV_LE_NAME VARCHAR2(200);
BEGIN
    SELECT HAUFT_LEG.NAME
    INTO LV_LE_NAME
    FROM HR_ORGANIZATION_UNITS_F_TL HAUFT_LEG
          ,HR_ALL_ORGANIZATION_UNITS_F HAOUF_LEG
          ,HR_ORG_UNIT_CLASSIFICATIONS_F HOUCF_LEG
          ,PER_ALL_ASSIGNMENTS_M PAAM2
    WHERE HAOUF_LEG.ORGANIZATION_ID = HAUFT_LEG.ORGANIZATION_ID
    AND HAOUF_LEG.ORGANIZATION_ID = HOUCF_LEG.ORGANIZATION_ID
    AND HOUCF_LEG.CLASSIFICATION_CODE = 'HCM_LEMP'
    AND PAAM2.ASSIGNMENT_ID = P_ASSIGNMENT_ID
    AND PAAM2.LEGAL_ENTITY_ID = HAOUF_LEG.ORGANIZATION_ID
    AND HAUFT_LEG.LANGUAGE = 'US'
    AND TRUNC(SYSDATE) BETWEEN HOUCF_LEG.EFFECTIVE_START_DATE AND HOUCF_LEG.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN HAOUF_LEG.EFFECTIVE_START_DATE AND HAOUF_LEG.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN HAUFT_LEG.EFFECTIVE_START_DATE AND HAUFT_LEG.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN PAAM2.EFFECTIVE_START_DATE AND PAAM2.EFFECTIVE_END_DATE
    AND ROWNUM = 1;
    RETURN LV_LE_NAME;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END;
FUNCTION GET_COST_CENTER_BY_ORG_ID(P_ORG_ID NUMBER) RETURN VARCHAR2 DETERMINISTIC AS
    LV_COST_CENTER VARCHAR2(200);
BEGIN
    SELECT PCAA.SEGMENT1 || '-' || PCAA.SEGMENT2
    INTO LV_COST_CENTER
    FROM PAY_COST_ALLOC_ACCOUNTS PCAA
          ,PAY_COST_ALLOCATIONS_F PCAF
          ,HR_ALL_ORGANIZATION_UNITS_F HAOUF_LE
          ,HR_ORGANIZATION_UNITS_F_TL HAUFT_LE
          ,HR_ORG_UNIT_CLASSIFICATIONS_F HOUCF_DEP
          ,HR_ALL_ORGANIZATION_UNITS_F HAOUF_DEP
          ,HR_ORGANIZATION_UNITS_F_TL HAUFT_DEP
    WHERE PCAA.COST_ALLOCATION_RECORD_ID = PCAF.COST_ALLOCATION_RECORD_ID
    AND PCAA.SOURCE_SUB_TYPE = 'COST'
    AND PCAF.SOURCE_ID = HAOUF_LE.ORGANIZATION_ID
    AND HAOUF_LE.ORGANIZATION_ID = HAUFT_LE.ORGANIZATION_ID
    AND HAUFT_LE.LANGUAGE = 'US'
    AND TRUNC(SYSDATE) BETWEEN HAOUF_LE.EFFECTIVE_START_DATE AND HAOUF_LE.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN HAUFT_LE.EFFECTIVE_START_DATE AND HAUFT_LE.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN PCAF.EFFECTIVE_START_DATE AND PCAF.EFFECTIVE_END_DATE
    AND HAOUF_DEP.ORGANIZATION_ID = HAUFT_DEP.ORGANIZATION_ID
    AND HAOUF_DEP.ORGANIZATION_ID = HOUCF_DEP.ORGANIZATION_ID
    AND HOUCF_DEP.CLASSIFICATION_CODE = 'DEPARTMENT'
    AND HOUCF_DEP.ORGANIZATION_ID = P_ORG_ID
    AND HAUFT_DEP.LANGUAGE = 'US'
    AND TRUNC(SYSDATE) BETWEEN HOUCF_DEP.EFFECTIVE_START_DATE AND HOUCF_DEP.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN HAOUF_DEP.EFFECTIVE_START_DATE AND HAOUF_DEP.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN HAUFT_DEP.EFFECTIVE_START_DATE AND HAUFT_DEP.EFFECTIVE_END_DATE
    AND HAUFT_LE.NAME = HAUFT_DEP.NAME
    AND ROWNUM = 1;
    RETURN LV_COST_CENTER;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END;
FUNCTION GET_COST_CENTER_BY_DEPT_NAME(P_DEPT_NAME VARCHAR2) RETURN VARCHAR2 DETERMINISTIC AS
    LV_COST_CENTER VARCHAR2(200);
BEGIN
    SELECT PCAA.SEGMENT1 || '-' || PCAA.SEGMENT2
    INTO LV_COST_CENTER
    FROM PAY_COST_ALLOC_ACCOUNTS PCAA
          ,PAY_COST_ALLOCATIONS_F PCAF
          ,HR_ALL_ORGANIZATION_UNITS_F HAOUF_LE
          ,HR_ORGANIZATION_UNITS_F_TL HAUFT_LE
    WHERE PCAA.COST_ALLOCATION_RECORD_ID = PCAF.COST_ALLOCATION_RECORD_ID
    AND PCAA.SOURCE_SUB_TYPE = 'COST'
    AND PCAF.SOURCE_ID = HAOUF_LE.ORGANIZATION_ID
    AND HAOUF_LE.ORGANIZATION_ID = HAUFT_LE.ORGANIZATION_ID
    AND HAUFT_LE.LANGUAGE = 'US'
    AND TRUNC(SYSDATE) BETWEEN HAOUF_LE.EFFECTIVE_START_DATE AND HAOUF_LE.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN HAUFT_LE.EFFECTIVE_START_DATE AND HAUFT_LE.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN PCAF.EFFECTIVE_START_DATE AND PCAF.EFFECTIVE_END_DATE
    AND HAUFT_LE.NAME = P_DEPT_NAME
    AND ROWNUM = 1;
    RETURN LV_COST_CENTER;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END;
FUNCTION GET_CSP(P_GRADE_PREFIX VARCHAR2) RETURN VARCHAR2 DETERMINISTIC AS
    LV_CSP VARCHAR2(200);
BEGIN
    SELECT SUBSTR(FUCI.VALUE, 1, 100)
    INTO LV_CSP
    FROM FF_USER_TABLES_VL FUT
          ,FF_USER_COLUMNS_VL FUC
          ,FF_USER_ROWS_VL FUR
          ,FF_USER_COLUMN_INSTANCES_F FUCI
          ,PER_LEGISLATIVE_DATA_GROUPS_VL LDG
    WHERE FUT.USER_TABLE_ID = FUC.USER_TABLE_ID
    AND FUT.USER_TABLE_ID = FUR.USER_TABLE_ID
    AND FUC.USER_COLUMN_ID = FUCI.USER_COLUMN_ID
    AND FUR.USER_ROW_ID = FUCI.USER_ROW_ID
    AND TRUNC(SYSDATE) BETWEEN FUR.EFFECTIVE_START_DATE AND FUR.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN FUCI.EFFECTIVE_START_DATE AND FUCI.EFFECTIVE_END_DATE
    AND FUT.USER_TABLE_NAME = '<FASTFORMULA_USER_TABLE>'
    AND FUT.LEGISLATIVE_DATA_GROUP_ID = LDG.LEGISLATIVE_DATA_GROUP_ID
    AND FUC.USER_COLUMN_NAME = '<FASTFORMULA_USER_COLUMN>'
    AND FUR.ROW_NAME = P_GRADE_PREFIX;
    RETURN LV_CSP;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END;
FUNCTION GET_GRADE_CODE_BY_POSITION(P_POSITION_CODE VARCHAR2) RETURN VARCHAR2 DETERMINISTIC AS
    LV_GRADE_CODE VARCHAR2(200);
BEGIN
    SELECT GD.GRADE_CODE
    INTO LV_GRADE_CODE
    FROM HR_ALL_POSITIONS_F_VL HAPF
          ,PER_GRADES_F_VL GD
    WHERE HAPF.POSITION_CODE = P_POSITION_CODE
    AND TRUNC(SYSDATE) BETWEEN HAPF.EFFECTIVE_START_DATE AND HAPF.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN GD.EFFECTIVE_START_DATE AND GD.EFFECTIVE_END_DATE
    AND HAPF.ENTRY_GRADE_ID = GD.GRADE_ID
    AND HAPF.ACTIVE_STATUS = 'A'
    AND ROWNUM = 1;
    RETURN LV_GRADE_CODE;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END;
FUNCTION GET_JOB_CODE_BY_POSITION(P_POSITION_CODE VARCHAR2) RETURN VARCHAR2 DETERMINISTIC AS
    LV_JOB_CODE VARCHAR2(200);
BEGIN
    SELECT JOB.JOB_CODE
    INTO LV_JOB_CODE
    FROM HR_ALL_POSITIONS_F_VL HAPF
          ,PER_JOBS_F_VL JOB
    WHERE HAPF.POSITION_CODE = P_POSITION_CODE
    AND TRUNC(SYSDATE) BETWEEN HAPF.EFFECTIVE_START_DATE AND HAPF.EFFECTIVE_END_DATE
    AND TRUNC(SYSDATE) BETWEEN JOB.EFFECTIVE_START_DATE AND JOB.EFFECTIVE_END_DATE
    AND HAPF.JOB_ID = JOB.JOB_ID
    AND HAPF.ACTIVE_STATUS = 'A'
    AND ROWNUM = 1;
    RETURN LV_JOB_CODE;
EXCEPTION
    WHEN OTHERS THEN RETURN NULL;
END;
TAM_RAW AS (
    SELECT
           PAT.ALLOCATED_CHECKLIST_ID AS JOIN_CHECKLIST_ID
          ,PAT.ATTRIBUTE1, PAT.ATTRIBUTE2, PAT.ATTRIBUTE3, PAT.ATTRIBUTE4, PAT.ATTRIBUTE5
    FROM PER_ALLOCATED_TASKS PAT
          ,PER_ALLOCATED_TASKS_TL PAT_TL
    WHERE PAT.ALLOCATED_TASK_ID = PAT_TL.ALLOCATED_TASK_ID
    AND PAT_TL.LANGUAGE = 'US'
    AND PAT_TL.TASK_NAME IN ('<TASK_NAME_TAM_1>', '<TASK_NAME_TAM_2>')
    UNION ALL
    SELECT PAT.ABS_ALLOCATED_CHECKLIST_ID
          ,PAT.ATTRIBUTE1, PAT.ATTRIBUTE2, PAT.ATTRIBUTE3, PAT.ATTRIBUTE4, PAT.ATTRIBUTE5
    FROM PER_ALLOCATED_TASKS PAT
          ,PER_ALLOCATED_TASKS_TL PAT_TL
    WHERE PAT.ALLOCATED_TASK_ID = PAT_TL.ALLOCATED_TASK_ID
    AND PAT_TL.LANGUAGE = 'US'
    AND PAT_TL.TASK_NAME IN ('<TASK_NAME_TAM_1>', '<TASK_NAME_TAM_2>')
    AND PAT.ABS_ALLOCATED_CHECKLIST_ID IS NOT NULL
),
TAM_ALL AS (
    SELECT JOIN_CHECKLIST_ID, ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5
    FROM (
        SELECT T.*,
               ROW_NUMBER() OVER (PARTITION BY JOIN_CHECKLIST_ID ORDER BY ATTRIBUTE1) AS RN
        FROM TAM_RAW T
    )
    WHERE RN = 1
),
INT_RAW AS (
    SELECT
           PAT.ALLOCATED_CHECKLIST_ID AS JOIN_CHECKLIST_ID
          ,PAT.ALLOCATED_TASK_ID
          ,PAT.ATTRIBUTE1, PAT.ATTRIBUTE2, PAT.ATTRIBUTE3, PAT.ATTRIBUTE4, PAT.ATTRIBUTE5
          ,PAT.ATTRIBUTE7, PAT.ATTRIBUTE8, PAT.ATTRIBUTE9, PAT.ATTRIBUTE10, PAT.ATTRIBUTE11
          ,PAT.ATTRIBUTE12, PAT.ATTRIBUTE13, PAT.ATTRIBUTE14, PAT.ATTRIBUTE15
          ,PAT.ATTRIBUTE17, PAT.ATTRIBUTE18, PAT.ATTRIBUTE21
          ,PAT.ATTRIBUTE_NUMBER1, PAT.ATTRIBUTE_NUMBER2
          ,PAT.ATTRIBUTE_DATE1, PAT.ATTRIBUTE_DATE2
    FROM PER_ALLOCATED_TASKS PAT
          ,PER_ALLOCATED_TASKS_TL PAT_TL
    WHERE PAT.ALLOCATED_TASK_ID = PAT_TL.ALLOCATED_TASK_ID
    AND PAT_TL.LANGUAGE = 'US'
    AND PAT.STATUS = 'COM'
    AND PAT_TL.TASK_NAME IN (
                 '<TASK_NAME_INTAKE_1>'
                ,'<TASK_NAME_INTAKE_2>'
                ,'<TASK_NAME_INTAKE_3>'
                ,'<TASK_NAME_INTAKE_4>'
           )
    UNION ALL
    SELECT PAT.ABS_ALLOCATED_CHECKLIST_ID
          ,PAT.ALLOCATED_TASK_ID
          ,PAT.ATTRIBUTE1, PAT.ATTRIBUTE2, PAT.ATTRIBUTE3, PAT.ATTRIBUTE4, PAT.ATTRIBUTE5
          ,PAT.ATTRIBUTE7, PAT.ATTRIBUTE8, PAT.ATTRIBUTE9, PAT.ATTRIBUTE10, PAT.ATTRIBUTE11
          ,PAT.ATTRIBUTE12, PAT.ATTRIBUTE13, PAT.ATTRIBUTE14, PAT.ATTRIBUTE15
          ,PAT.ATTRIBUTE17, PAT.ATTRIBUTE18, PAT.ATTRIBUTE21
          ,PAT.ATTRIBUTE_NUMBER1, PAT.ATTRIBUTE_NUMBER2
          ,PAT.ATTRIBUTE_DATE1, PAT.ATTRIBUTE_DATE2
    FROM PER_ALLOCATED_TASKS PAT
          ,PER_ALLOCATED_TASKS_TL PAT_TL
    WHERE PAT.ALLOCATED_TASK_ID = PAT_TL.ALLOCATED_TASK_ID
    AND PAT_TL.LANGUAGE = 'US'
    AND PAT.STATUS = 'COM'
    AND PAT_TL.TASK_NAME IN (
                  '<TASK_NAME_INTAKE_1>'
                ,'<TASK_NAME_INTAKE_2>'
                ,'<TASK_NAME_INTAKE_3>'
                ,'<TASK_NAME_INTAKE_4>'
           )
    AND PAT.ABS_ALLOCATED_CHECKLIST_ID IS NOT NULL
),
INT_ALL AS (
    SELECT JOIN_CHECKLIST_ID, ALLOCATED_TASK_ID
          ,ATTRIBUTE1, ATTRIBUTE2, ATTRIBUTE3, ATTRIBUTE4, ATTRIBUTE5
          ,ATTRIBUTE7, ATTRIBUTE8, ATTRIBUTE9, ATTRIBUTE10, ATTRIBUTE11
          ,ATTRIBUTE12, ATTRIBUTE13, ATTRIBUTE14, ATTRIBUTE15
          ,ATTRIBUTE17, ATTRIBUTE18, ATTRIBUTE21
          ,ATTRIBUTE_NUMBER1, ATTRIBUTE_NUMBER2
          ,ATTRIBUTE_DATE1, ATTRIBUTE_DATE2
    FROM (
        SELECT I.*,
               ROW_NUMBER() OVER (PARTITION BY JOIN_CHECKLIST_ID ORDER BY ALLOCATED_TASK_ID) AS RN
        FROM INT_RAW I
    )
    WHERE RN = 1
),
POS_ALL AS (
    SELECT
           POS.ALLOCATED_CHECKLIST_ID AS JOIN_CHECKLIST_ID
          ,POS.ATTRIBUTE1, POS.ATTRIBUTE2, POS.ATTRIBUTE4, POS.ATTRIBUTE5
          ,POS.ATTRIBUTE7, POS.ATTRIBUTE9, POS.ATTRIBUTE10, POS.ATTRIBUTE11
          ,POS.ATTRIBUTE12, POS.ATTRIBUTE13
          ,POS.ATTRIBUTE_NUMBER1, POS.ATTRIBUTE_NUMBER2
          ,POS.TASK_COMMENTS, POS.ATTRIBUTE15, POS.ATTRIBUTE16
    FROM PER_ALLOCATED_TASKS POS
          ,PER_ALLOCATED_TASKS_TL POS_TL
    WHERE POS.ALLOCATED_TASK_ID = POS_TL.ALLOCATED_TASK_ID
    AND POS_TL.LANGUAGE = 'US'
    AND POS_TL.TASK_NAME = '<TASK_NAME_POSITION_SELECTION>'
    AND POS.ATTRIBUTE1 IN ('Existing Position', 'New Position')
    UNION ALL
    SELECT POS.ABS_ALLOCATED_CHECKLIST_ID
          ,POS.ATTRIBUTE1, POS.ATTRIBUTE2, POS.ATTRIBUTE4, POS.ATTRIBUTE5
          ,POS.ATTRIBUTE7, POS.ATTRIBUTE9, POS.ATTRIBUTE10, POS.ATTRIBUTE11
          ,POS.ATTRIBUTE12, POS.ATTRIBUTE13
          ,POS.ATTRIBUTE_NUMBER1, POS.ATTRIBUTE_NUMBER2
          ,POS.TASK_COMMENTS, POS.ATTRIBUTE15, POS.ATTRIBUTE16
    FROM PER_ALLOCATED_TASKS POS
          ,PER_ALLOCATED_TASKS_TL POS_TL
    WHERE POS.ALLOCATED_TASK_ID = POS_TL.ALLOCATED_TASK_ID
    AND POS_TL.LANGUAGE = 'US'
    AND POS_TL.TASK_NAME = '<TASK_NAME_POSITION_SELECTION>'
    AND POS.ATTRIBUTE1 IN ('Existing Position', 'New Position')
    AND POS.ABS_ALLOCATED_CHECKLIST_ID IS NOT NULL
),
JD_RAW AS (
    SELECT
           PAT.ALLOCATED_CHECKLIST_ID AS JOIN_CHECKLIST_ID
          ,PAT.ALLOCATED_TASK_ID
          ,PAT.ATTRIBUTE1
    FROM PER_ALLOCATED_TASKS PAT
          ,PER_ALLOCATED_TASKS_TL PAT_TL
    WHERE PAT.ALLOCATED_TASK_ID = PAT_TL.ALLOCATED_TASK_ID
    AND PAT_TL.LANGUAGE = 'US'
    AND PAT_TL.TASK_NAME = '<TASK_NAME_JOB_DESC>'
    UNION ALL
    SELECT PAT.ABS_ALLOCATED_CHECKLIST_ID
          ,PAT.ALLOCATED_TASK_ID
          ,PAT.ATTRIBUTE1
    FROM PER_ALLOCATED_TASKS PAT
          ,PER_ALLOCATED_TASKS_TL PAT_TL
    WHERE PAT.ALLOCATED_TASK_ID = PAT_TL.ALLOCATED_TASK_ID
    AND PAT_TL.LANGUAGE = 'US'
    AND PAT_TL.TASK_NAME = '<TASK_NAME_JOB_DESC>'
    AND PAT.ABS_ALLOCATED_CHECKLIST_ID IS NOT NULL
),
JD_ALL AS (
    SELECT JOIN_CHECKLIST_ID, ATTRIBUTE1
    FROM (
        SELECT J.*,
               ROW_NUMBER() OVER (PARTITION BY JOIN_CHECKLIST_ID ORDER BY ALLOCATED_TASK_ID DESC) AS RN
        FROM JD_RAW J
    )
    WHERE RN = 1
),
PAPF_ONE AS (
    SELECT PERSON_ID, PERSON_NUMBER
    FROM (
        SELECT PAPF.PERSON_ID, PAPF.PERSON_NUMBER,
               ROW_NUMBER() OVER (
                   PARTITION BY PAPF.PERSON_ID
                   ORDER BY PAPF.EFFECTIVE_START_DATE DESC, PAPF.PERSON_NUMBER
               ) AS RN
        FROM PER_ALL_PEOPLE_F PAPF
        WHERE TRUNC(SYSDATE) BETWEEN PAPF.EFFECTIVE_START_DATE AND PAPF.EFFECTIVE_END_DATE
    )
    WHERE RN = 1
),
HM_ALL AS (
    SELECT DISTINCT
           PAC.ALLOCATED_CHECKLIST_ID AS JOIN_CHECKLIST_ID
          ,REGEXP_SUBSTR(PAT.ATTRIBUTE14, '^[0-9]+') AS HM_PERSON_NUMBER
    FROM PER_ALLOCATED_CHECKLISTS PAC
          ,PER_ALLOCATED_TASKS_VL PAT
          ,PER_USERS PU
          ,PER_USER_ROLES PUR
          ,PER_ROLES_DN PRD
    WHERE (
                PAT.ALLOCATED_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
             OR PAT.ABS_ALLOCATED_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
           )
    AND PAT.TASK_PERFORMERS = PU.USER_GUID
    AND PU.USER_ID = PUR.USER_ID
    AND PUR.ROLE_ID = PRD.ROLE_ID
    AND PAT.TASK_NAME = '<TASK_NAME_POSITION_SELECTION>'
    AND PRD.ROLE_COMMON_NAME = '<HIRING_MANAGER_ROLE_NAME>'
),
LATEST_REQ AS (
    SELECT NVL(MAX(TO_NUMBER(REGEXP_SUBSTR(REQUISITION_NUMBER, '[0-9]+$'))), 0) AS LATEST_NUM
    FROM IRC_REQUISITIONS_VL
),
REQNUM_BASE AS (
    SELECT
           DISTINCT PAC.ALLOCATED_CHECKLIST_ID
    FROM PER_ALLOCATED_CHECKLISTS PAC
          ,POS_ALL
          ,TAM_ALL
          ,PER_ALL_ASSIGNMENTS_M PAAM
          ,INT_ALL
    WHERE PAC.CHECKLIST_STATUS = 'COM'
    AND POS_ALL.JOIN_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
    AND TAM_ALL.JOIN_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
    AND PAAM.ASSIGNMENT_ID = PAC.ASSIGNMENT_ID
    AND TRUNC(SYSDATE) BETWEEN PAAM.EFFECTIVE_START_DATE AND PAAM.EFFECTIVE_END_DATE
    AND INT_ALL.JOIN_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
    AND (
            ( POS_ALL.ATTRIBUTE1 = 'Existing Position'
              AND EXISTS (
                    SELECT 1
                    FROM HR_ALL_POSITIONS_F_VL H2
                    WHERE H2.POSITION_CODE = TRIM(SUBSTR(POS_ALL.ATTRIBUTE2, INSTR(POS_ALL.ATTRIBUTE2, '-', -1) + 1))
                    AND TRUNC(SYSDATE) BETWEEN H2.EFFECTIVE_START_DATE AND H2.EFFECTIVE_END_DATE
                    AND EXISTS (SELECT 1 FROM FUN_ALL_BUSINESS_UNITS_V BUX WHERE BUX.BU_ID = H2.BUSINESS_UNIT_ID)
                  )
            )
         OR
            ( POS_ALL.ATTRIBUTE1 = 'New Position'
              AND EXISTS (SELECT 1 FROM FUN_ALL_BUSINESS_UNITS_V BUY WHERE BUY.BU_ID = PAAM.BUSINESS_UNIT_ID)
            )
        )
    AND NOT EXISTS (
        SELECT 1
        FROM HRC_INTEGRATION_KEY_MAP HIM
        WHERE HIM.OBJECT_NAME = 'Requisition'
        AND HIM.SOURCE_SYSTEM_ID = TO_CHAR(PAC.ALLOCATED_CHECKLIST_ID)
    )
),
REQNUM_MAP AS (
    SELECT ALLOCATED_CHECKLIST_ID
          ,(SELECT LATEST_NUM FROM LATEST_REQ)
             + ROW_NUMBER() OVER (ORDER BY ALLOCATED_CHECKLIST_ID) AS REQUISITIONNUMBER
    FROM REQNUM_BASE
),
MAIN_ROWS AS (
SELECT
     'JobRequisition' AS JOBREQUISITION
    ,'US' AS BASELANGUAGECODE
    ,RM.REQUISITIONNUMBER AS REQUISITIONNUMBER
    ,NVL(HM_ALL.HM_PERSON_NUMBER, PAPF.PERSON_NUMBER) AS HIRINGMANAGERPERSONNUMBER
    ,PAC.CHECKLIST_STATUS AS STATUS
    ,PAC.ALLOCATED_CHECKLIST_ID AS SOURCESYSTEMID
    ,'<SOURCE_SYSTEM_OWNER>' AS SOURCESYSTEMOWNER
    ,POS_ALL.ATTRIBUTE1 AS POSITION_SELECTION_TYPE
    ,DECODE(POS_ALL.ATTRIBUTE1,'New Position','ORA_NEW_POSITION','Existing Position','ORA_REPLACEMENT') AS BUSINESSJUSTIFICATION
    ,CASE POS_ALL.ATTRIBUTE1
        WHEN 'Existing Position' THEN TRIM(SUBSTR(POS_ALL.ATTRIBUTE2, 1, INSTR(POS_ALL.ATTRIBUTE2, '-', -1) - 1))
        WHEN 'New Position' THEN POS_ALL.ATTRIBUTE5
     END AS REQUISITIONTITLE
    ,CASE POS_ALL.ATTRIBUTE1
        WHEN 'Existing Position' THEN POS_ALL.ATTRIBUTE2
        WHEN 'New Position' THEN POS_ALL.ATTRIBUTE5
     END AS POSITION
    ,CASE POS_ALL.ATTRIBUTE1
        WHEN 'Existing Position' THEN TRIM(SUBSTR(POS_ALL.ATTRIBUTE2, INSTR(POS_ALL.ATTRIBUTE2, '-', -1) + 1))
        WHEN 'New Position' THEN JD_ALL.ATTRIBUTE1
     END AS POSITIONCODE
    ,CASE POS_ALL.ATTRIBUTE1
        WHEN 'Existing Position' THEN TO_CHAR(POS_ALL.ATTRIBUTE_NUMBER2)
        WHEN 'New Position' THEN TO_CHAR(POS_ALL.ATTRIBUTE_NUMBER1)
     END AS NUMBEROFOPENINGS
    ,CASE POS_ALL.ATTRIBUTE1
        WHEN 'Existing Position' THEN (
            SELECT BU2.BU_NAME
            FROM HR_ALL_POSITIONS_F_VL H2, FUN_ALL_BUSINESS_UNITS_V BU2
            WHERE H2.POSITION_CODE = TRIM(SUBSTR(POS_ALL.ATTRIBUTE2, INSTR(POS_ALL.ATTRIBUTE2, '-', -1) + 1))
            AND TRUNC(SYSDATE) BETWEEN H2.EFFECTIVE_START_DATE AND H2.EFFECTIVE_END_DATE
            AND BU2.BU_ID = H2.BUSINESS_UNIT_ID
            AND ROWNUM = 1
        )
        WHEN 'New Position' THEN GET_BU_BY_POSITION(JD_ALL.ATTRIBUTE1)
     END AS BUSINESSUNITSHORTCODE
    ,CASE POS_ALL.ATTRIBUTE1
        WHEN 'Existing Position' THEN GET_DEPARTMENT_NAME(PAAM.ORGANIZATION_ID)
        WHEN 'New Position' THEN POS_ALL.ATTRIBUTE7
     END AS DEPARTMENT
    ,CASE POS_ALL.ATTRIBUTE1
        WHEN 'Existing Position' THEN GET_DEPARTMENT_ORG_ID(PAAM.ORGANIZATION_ID)
        WHEN 'New Position' THEN GET_ORG_ID_BY_POSITION(JD_ALL.ATTRIBUTE1)
     END AS ORGANIZATIONID
    ,CASE POS_ALL.ATTRIBUTE1
        WHEN 'Existing Position' THEN GET_JOB_BY_JOB_ID(PAAM.JOB_ID)
        WHEN 'New Position' THEN GET_JOB_BY_POSITION(JD_ALL.ATTRIBUTE1)
     END AS JOB
    ,POS_ALL.ATTRIBUTE10 AS PRIMARYLOCATIONNAME
    ,CASE POS_ALL.ATTRIBUTE1
        WHEN 'Existing Position' THEN GET_GRADE_NAME(PAAM.GRADE_ID)
        WHEN 'New Position' THEN POS_ALL.ATTRIBUTE11
     END AS GRADE
    ,CASE POS_ALL.ATTRIBUTE1
        WHEN 'Existing Position' THEN
            GET_GRADE_CODE_BY_POSITION(
                TRIM(SUBSTR(POS_ALL.ATTRIBUTE2, INSTR(POS_ALL.ATTRIBUTE2, '-', -1) + 1))
            )
        WHEN 'New Position' THEN
            GET_GRADE_CODE_BY_POSITION(JD_ALL.ATTRIBUTE1)
     END AS GRADECODE
    ,CASE POS_ALL.ATTRIBUTE1
        WHEN 'Existing Position' THEN
            GET_JOB_CODE_BY_POSITION(
                TRIM(SUBSTR(POS_ALL.ATTRIBUTE2, INSTR(POS_ALL.ATTRIBUTE2, '-', -1) + 1))
            )
        WHEN 'New Position' THEN
            GET_JOB_CODE_BY_POSITION(JD_ALL.ATTRIBUTE1)
     END AS JOBCODE
    ,TRIM(SUBSTR(TAM_ALL.ATTRIBUTE1, INSTR(TAM_ALL.ATTRIBUTE1, '-') + 1)) AS RECRUITERPERSONNUMBER
    ,TAM_ALL.ATTRIBUTE2 AS COLLABORATOR1
    ,TAM_ALL.ATTRIBUTE3 AS COLLABORATOR2
    ,'REQUISITION_DRAFT' AS CURRENTPHASECODE
    ,'REQUISITION_IN_PROGRESS' AS CURRENTSTATECODE
    ,'Global Data Elements' AS "FLEX:IRC_REQUISITIONS_DFF"
    ,'N' AS UNLIMITEDOPENINGSFLAG
    ,'ORA_PROFESSIONAL' AS RECRUITINGTYPE
    ,'E' AS WORKERTYPE
    ,CASE POS_ALL.ATTRIBUTE1
        WHEN 'Existing Position' THEN
            GET_CSP(TRIM(SUBSTR(GET_GRADE_NAME(PAAM.GRADE_ID), 1,
                        CASE WHEN INSTR(GET_GRADE_NAME(PAAM.GRADE_ID), ' - ') > 0
                             THEN INSTR(GET_GRADE_NAME(PAAM.GRADE_ID), ' - ') - 1
                             ELSE LENGTH(GET_GRADE_NAME(PAAM.GRADE_ID))
                        END)))
        WHEN 'New Position' THEN
            GET_CSP(TRIM(SUBSTR(POS_ALL.ATTRIBUTE11, 1,
                        CASE WHEN INSTR(POS_ALL.ATTRIBUTE11, ' - ') > 0
                             THEN INSTR(POS_ALL.ATTRIBUTE11, ' - ') - 1
                             ELSE LENGTH(POS_ALL.ATTRIBUTE11)
                        END)))
     END AS CANDIDATESELECTIONPROCESSCODE
    ,GET_LEGAL_EMPLOYER(PAAM.ASSIGNMENT_ID) AS LEGALEMPLOYERNAME
    ,CASE POS_ALL.ATTRIBUTE1
        WHEN 'Existing Position' THEN GET_COST_CENTER_BY_ORG_ID(PAAM.ORGANIZATION_ID)
        WHEN 'New Position' THEN GET_COST_CENTER_BY_DEPT_NAME(POS_ALL.ATTRIBUTE7)
     END AS COSTCENTER
    ,POS_ALL.ATTRIBUTE4 AS NATIONALITYTYPE
    ,POS_ALL.ATTRIBUTE13 AS NUMBERWORKINGDAYSPERWEEK
    ,POS_ALL.TASK_COMMENTS AS COMMENTSJUSTIFICATION
    ,POS_ALL.ATTRIBUTE15 AS CONTRACTTERM
    ,POS_ALL.ATTRIBUTE16 AS LOCATIONTYPE
    ,TO_CHAR(POS_ALL.ATTRIBUTE_NUMBER1) AS DURATIONOFREQUIREMENTINYEAR
FROM
     PER_ALLOCATED_CHECKLISTS PAC
    JOIN PAPF_ONE PAPF
      ON PAPF.PERSON_ID = PAC.PERSON_ID
    JOIN POS_ALL
      ON POS_ALL.JOIN_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
    JOIN TAM_ALL
      ON TAM_ALL.JOIN_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
    JOIN PER_ALL_ASSIGNMENTS_M PAAM
      ON PAAM.ASSIGNMENT_ID = PAC.ASSIGNMENT_ID
     AND TRUNC(SYSDATE) BETWEEN PAAM.EFFECTIVE_START_DATE AND PAAM.EFFECTIVE_END_DATE
    JOIN INT_ALL
      ON INT_ALL.JOIN_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
    LEFT JOIN JD_ALL
      ON JD_ALL.JOIN_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
    LEFT JOIN REQNUM_MAP RM
      ON RM.ALLOCATED_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
    LEFT JOIN HM_ALL
      ON HM_ALL.JOIN_CHECKLIST_ID = PAC.ALLOCATED_CHECKLIST_ID
WHERE 1=1
    AND PAC.CHECKLIST_ID = '<CHECKLIST_ID>'
    AND PAC.CHECKLIST_STATUS = 'COM'
    AND (
            ( POS_ALL.ATTRIBUTE1 = 'Existing Position'
              AND EXISTS (
                    SELECT 1
                    FROM HR_ALL_POSITIONS_F_VL H2
                    WHERE H2.POSITION_CODE = TRIM(SUBSTR(POS_ALL.ATTRIBUTE2, INSTR(POS_ALL.ATTRIBUTE2, '-', -1) + 1))
                    AND TRUNC(SYSDATE) BETWEEN H2.EFFECTIVE_START_DATE AND H2.EFFECTIVE_END_DATE
                    AND EXISTS (SELECT 1 FROM FUN_ALL_BUSINESS_UNITS_V BUX WHERE BUX.BU_ID = H2.BUSINESS_UNIT_ID)
                  )
            )
         OR
            ( POS_ALL.ATTRIBUTE1 = 'New Position'
              AND EXISTS (SELECT 1 FROM FUN_ALL_BUSINESS_UNITS_V BUY WHERE BUY.BU_ID = PAAM.BUSINESS_UNIT_ID)
            )
        )
    /*AND (PAPF.PERSON_NUMBER = :P_PERSON_NUMBER OR :P_PERSON_NUMBER IS NULL)
    AND (PAC.ALLOCATED_CHECKLIST_ID = :P_ALLOCATED_CHECKLIST_ID OR :P_ALLOCATED_CHECKLIST_ID IS NULL)*/
    AND NOT EXISTS (
        SELECT 1
        FROM HRC_INTEGRATION_KEY_MAP HIM
        WHERE HIM.OBJECT_NAME = 'Requisition'
        AND HIM.SOURCE_SYSTEM_ID = TO_CHAR(PAC.ALLOCATED_CHECKLIST_ID)
    )
)
SELECT
     JOBREQUISITION
    ,BASELANGUAGECODE
    ,REQUISITIONNUMBER
    ,HIRINGMANAGERPERSONNUMBER
    ,STATUS
    ,SOURCESYSTEMID
    ,SOURCESYSTEMOWNER
    ,POSITION_SELECTION_TYPE
    ,REQUISITIONTITLE
    ,POSITION
    ,POSITIONCODE
    ,NUMBEROFOPENINGS
    ,BUSINESSUNITSHORTCODE
    ,DEPARTMENT
    ,ORGANIZATIONID
    ,JOB
    ,BUSINESSJUSTIFICATION
    ,PRIMARYLOCATIONNAME
    ,GRADE
    ,GRADECODE
    ,JOBCODE
    ,RECRUITERPERSONNUMBER
    ,COLLABORATOR1
    ,COLLABORATOR2
    ,CURRENTPHASECODE
    ,CURRENTSTATECODE
    ,"FLEX:IRC_REQUISITIONS_DFF"
    ,UNLIMITEDOPENINGSFLAG
    ,RECRUITINGTYPE
    ,WORKERTYPE
    ,CANDIDATESELECTIONPROCESSCODE
    ,LEGALEMPLOYERNAME
    ,COSTCENTER
    ,NATIONALITYTYPE
    ,NUMBERWORKINGDAYSPERWEEK
    ,COMMENTSJUSTIFICATION
    ,CONTRACTTERM
    ,LOCATIONTYPE
    ,DURATIONOFREQUIREMENTINYEAR
FROM (
    SELECT MAIN_ROWS.*,
           ROW_NUMBER() OVER (
               PARTITION BY SOURCESYSTEMID
               ORDER BY SOURCESYSTEMID
           ) AS RN__DEDUP
    FROM MAIN_ROWS
)
WHERE RN__DEDUP = 1
